### ISSUE TITLE
POSTGRES_DB: customer in compose.yml

### ISSUE THREAD

**Issue by hazartilirot** [amigoscode/full-stack-professional#11]
Basically, if you open the [official docker postgres page](https://registry.hub.docker.com/_/postgres) there would be the subject's description.
You just need to add this line to your **compose.yml** file in order to create the default database **customer**
**POSTGRES_DB: customer**

```yml
version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - 5432:5432
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
  db:
```
